'use strict';
const form=document.getElementById('plan-form');
document.getElementById('trailers').innerHTML=SortPlanner.trailers.map(t=>`<tr><th>${t.id}</th><td><input aria-label="${t.id} arrival minute" type="number" min="0" max="480" step="1" value="${t.arrival}" data-arrival="${t.id}"></td><td><input aria-label="${t.id} packages" type="number" min="1" max="50000" step="1" value="${t.volume}" data-volume="${t.id}"></td></tr>`).join('');
const fmt=n=>n===null?'Not completed':n.toLocaleString('en-US',{maximumFractionDigits:1});
function render(){try{
const p=Object.fromEntries(new FormData(form).entries());for(const k in p)p[k]=p[k].trim()===''?NaN:Number(p[k]);
const ts=SortPlanner.trailers.map(t=>({...t,arrival:read(`[data-arrival="${t.id}"]`),volume:read(`[data-volume="${t.id}"]`)}));
const {baseline:b,best:r,policy}=SortPlanner.plan(p,ts);
document.getElementById('error').textContent='';
document.getElementById('results').innerHTML=`<div class="kpis"><div><span>Packages by target</span><strong>${fmt(r.completed)}</strong></div><div><span>Finish in minutes</span><strong>${fmt(r.finish)}</strong></div><div><span>Assigned crew-hours</span><strong>${fmt(r.labor)}</strong></div></div><div class="panel"><h2>Recommended door staffing</h2><p>${r.crew.map((n,i)=>`Door ${i+1}: <b>${n}</b>`).join(' · ')} + ${p.support} support</p><p class="small">${policy}. ${p.crew-p.support-r.crew.reduce((a,b)=>a+b,0)} available workers left for redeployment.</p><div class="table-scroll"><table><caption>Same inputs, two plans</caption><thead><tr><th>Metric</th><th>Balanced queues</th><th>Recommendation</th></tr></thead><tbody><tr><th>Packages by ${p.target} min</th><td>${fmt(b.completed)}</td><td>${fmt(r.completed)}</td></tr><tr><th>Finish (min)</th><td>${fmt(b.finish)}</td><td>${fmt(r.finish)}</td></tr><tr><th>Assigned crew-hours</th><td>${fmt(b.labor)}</td><td>${fmt(r.labor)}</td></tr></tbody></table></div><p class="small">${fmt(r.completed-b.completed)} additional packages by target. ${b.labor!==null&&r.labor!==null?fmt(b.labor-r.labor)+' fewer assigned crew-hours.':'Completion and labor comparison unavailable.'} Simulated, not verified savings.</p><div class="table-scroll"><table><caption>Recommended trailer assignments</caption><thead><tr><th>Trailer</th><th>Door</th><th>Start min</th><th>Finish min</th></tr></thead><tbody>${r.jobs.map(j=>`<tr><th>${j.id}</th><td>${j.door===null?'—':j.door+1}</td><td>${j.start??'—'}</td><td>${fmt(j.end)}</td></tr>`).join('')}</tbody></table></div></div><br>`;
}catch(e){document.getElementById('error').textContent=e.message;document.getElementById('results').innerHTML='';}}
function read(selector){const v=document.querySelector(selector).value;return v.trim()===''?NaN:Number(v);}
form.addEventListener('submit',e=>{e.preventDefault();render();});render();
